# syntax=docker/dockerfile:1
FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive

RUN <<EOT bash
  apt-get update
  apt-get -y upgrade
  apt-get -y install ca-certificates
  apt-get -y install vim wget sudo git tar build-essential cmake curl python3 python3-pip python3-venv gdb valgrind htop strace
EOT
RUN apt-get clean

# Setup container user
ENV USER=ubuntu
RUN useradd --create-home -s /bin/bash -m $USER && echo "$USER:ubuntu" | chpasswd && adduser $USER sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# SIMD Everywhere
COPY simde/simde /usr/include/simde
COPY simde/README.md /home/ubuntu/README-simde.md

# AWS Porting Advisor for Graviton
#COPY porting-advisor-for-graviton /tmp/aws
#WORKDIR /tmp/aws
#RUN ./build.sh && cp dist/* /usr/sbin/

WORKDIR /home/ubuntu
USER ubuntu

